port:  4000
markdown: kramdown
name: Progressive Action Night
url: http://www.progressiveactionnight.org
title: Progressive Action Night
description: "To help coordinate and facilitate NYC trainings in preparation for the midterm elections and other important struggles, we are organizing a series of biweekly trainings and actions on Monday nights -- under the guise of Progressive Action Nights."
encoding: utf-8
timezone: America/New York
plugins_dir:
  - jekyll-redirect-from
  - kramdown
gems:
  - jekyll-redirect-from
future: true
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
