port:  4000
markdown: kramdown
name: Prog Hacknight
url: http://chihacknight.org
title: Prog Hacknight
description: "Chicago's weekly event to build, share, and learn about civic tech."
encoding: utf-8
timezone: America/Chicago
gems:
  - jekyll-redirect-from
future: true