port:  4000
markdown: kramdown
name: Prog Hacknight
url: http://proghacknight.org
title: Prog Hacknight
description: "The Progressive HackNight is dedicated to making great ideas happen. We embrace progressive ideals, and want our space to be safe, productive, and inspiring."
encoding: utf-8
timezone: America/Chicago
gems:
  - jekyll-redirect-from
future: true
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
